services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - bot_network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: bookbot_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_NODENAME: rabbit@rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - bot_network
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl -n rabbit@rabbitmq status || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=bookbot
      - POSTGRES_DB=bookbot
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pd-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - bot_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookbot -d bookbot"]
      interval: 3s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  migrations:
    image: ghcr.io/sasha4ka/barber-migrations:latest
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bot_network
    environment:
      - POSTGRES_URL=postgresql+asyncpg://bookbot:${POSTGRES_PASSWORD}@db:5432/bookbot

  bot:
    image: ghcr.io/sasha4ka/barber-bot:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    networks:
      - bot_network
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBHOOK_URL=https://{DOMAIN_NAME}/webhook
      - ADMIN_TG=${ADMIN_TG}
      - DEBUG=False
      - PROXY_URL=${PROXY_URL}
      - REDIS_URL=redis://redis:6379/0
      - RABBITMQ_URL=rabbitmq://user:${RABBITMQ_PASSWORD}@rabbitmq:5672/
      - POSTGRES_URL=postgresql+asyncpg://bookbot:${POSTGRES_PASSWORD}@db:5432/bookbot

  api:
    image: ghcr.io/sasha4ka/barber-api:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
    ports:
      - "9000:9000"
    networks:
      - bot_network
    environment:
      - RABBITMQ_URL=rabbitmq://user:${RABBITMQ_PASSWORD}@rabbitmq:5672/
      - POSTGRES_URL=postgresql+asyncpg://bookbot:${POSTGRES_PASSWORD}@db:5432/bookbot
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}

  notification_service:
    image: ghcr.io/sasha4ka/barber-notification-service:latest
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - bot_network
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - RABBITMQ_URL=rabbitmq://user:${RABBITMQ_PASSWORD}@rabbitmq:5672/
      - PROXY_URL=${PROXY_URL}

volumes:
  pd-data:
  redis-data:
  rabbitmq_data:

networks:
  bot_network:
    driver: bridge
