[project]
name = "bookbot-monorepo"
version = "0.1.0"
description = "Монорепозиторий книжного бота и сервиса уведомлений"
requires-python = "==3.14.*"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.3.0",
    "pytest>=8.0.0",
]

[tool.uv.workspace]
members = [
    "apps/bot",
    "apps/api",
    "apps/notification_service",
    "libs/core_shared"
]