"""fix: master.tg_id must be nullable

Revision ID: 0a2d1f206a60
Revises: bcf4b951cff3
Create Date: 2026-05-26 12:58:23.634303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a2d1f206a60'
down_revision: Union[str, Sequence[str], None] = 'bcf4b951cff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('masters', 'tg_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('masters', 'tg_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
