"""Add many appointments to one slot (for canceled appointments)

Revision ID: 1f4d6e0bef2c
Revises: bd2e0cc461f9
Create Date: 2026-05-20 16:15:01.818777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f4d6e0bef2c'
down_revision: Union[str, Sequence[str], None] = 'bd2e0cc461f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('appointments_slot_id_key'), 'appointments', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('appointments_slot_id_key'), 'appointments', ['slot_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
