"""Add many appointments to one slot (for canceled appointments)

Revision ID: 94a918422d00
Revises: 1f4d6e0bef2c
Create Date: 2026-05-20 16:24:00.115331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94a918422d00'
down_revision: Union[str, Sequence[str], None] = '1f4d6e0bef2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
