"""fix 2: master.tg_id must be nullable

Revision ID: a8cf2f0fd8f5
Revises: 0a2d1f206a60
Create Date: 2026-05-26 13:11:48.825170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8cf2f0fd8f5'
down_revision: Union[str, Sequence[str], None] = '0a2d1f206a60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
