"""add relationships Master - Slot

Revision ID: bcf4b951cff3
Revises: 9f6f45c1349e
Create Date: 2026-05-26 11:06:33.014326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcf4b951cff3'
down_revision: Union[str, Sequence[str], None] = '9f6f45c1349e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('masters',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.add_column('slots', sa.Column('master_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'slots', 'masters', ['master_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'slots', type_='foreignkey')
    op.drop_column('slots', 'master_id')
    op.drop_table('masters')
    # ### end Alembic commands ###
