"""fix: slot - appointment must be one to many because of canceled appointments

Revision ID: dbaea9e2069b
Revises: 51e68dd9797c
Create Date: 2026-05-31 13:27:17.214111

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dbaea9e2069b"
down_revision: Union[str, Sequence[str], None] = "51e68dd9797c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
