"""add master.username, master.password, master.token_version for authentication

Revision ID: dcfe1870768a
Revises: dbaea9e2069b
Create Date: 2026-06-04 14:02:03.818824

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dcfe1870768a"
down_revision: Union[str, Sequence[str], None] = "dbaea9e2069b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "masters", sa.Column("username", sa.String(length=64), nullable=False)
    )
    op.add_column(
        "masters", sa.Column("password_hash", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "masters",
        sa.Column("token_version", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "masters",
        sa.Column("is_admin", sa.Boolean(), server_default="false", nullable=False),
    )
    op.create_unique_constraint(None, "masters", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "masters", type_="unique")
    op.drop_column("masters", "is_admin")
    op.drop_column("masters", "token_version")
    op.drop_column("masters", "password_hash")
    op.drop_column("masters", "username")
    # ### end Alembic commands ###
