name: Build and Push Docker Image

on:
    push:
        branches: [ "main" ]

jobs:
    build-api:
        permissions:
            contents: read
            packages: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Log in to Github Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./apps/api/Dockerfile
                push: true
                tags: ghcr.io/sasha4ka/barber-api:latest
    build-bot:
        permissions:
            contents: read
            packages: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Log in to Github Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./apps/bot/Dockerfile
                push: true
                tags: ghcr.io/sasha4ka/barber-bot:latest

    build-notification-service:
        permissions:
            contents: read
            packages: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Log in to Github Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./apps/notification_service/Dockerfile
                push: true
                tags: ghcr.io/sasha4ka/barber-notification-service:latest

    build-migrations:
        permissions:
            contents: read
            packages: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Log in to Github Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./libs/core_shared/migrations.Dockerfile
                push: true
                tags: ghcr.io/sasha4ka/barber-migrations:latest